group: travis_latest

language: python
arch:
 - ppc64le

services:
  - docker

cache: pip

matrix:
  include:
    - python: "3.6"
      env: 
        - ONE_JOB_ONLY_TESTS=false
	- WIOTP_API_KEY=orgid-h798S7833DK
	- WIOTP_API_TOKEN=myauthtoken
    - python: "3.7"
      env: 
        - ONE_JOB_ONLY_TESTS=false
	- WIOTP_API_KEY=orgid-h798S7833DK
	- WIOTP_API_TOKEN=myauthtoken
    - python: "3.8"
      env: 
        - ONE_JOB_ONLY_TESTS=true
	- BUILD_DOCKER_IMAGES=true
        - WIOTP_API_KEY=orgid-h798S7833DK
	- WIOTP_API_TOKEN=myauthtoken

install: 
  - pip install tox-travis coveralls pyyaml
 
script: 
  - tox
  - ./buildDockerImages.sh

after_success:
  # Only upload coverage report from pythonn 3.8 test run if BUILD_DOCKER_IMAGES is not null and not empty
  - |
    if [ -n "${BUILD_DOCKER_IMAGES}" ]; then
      coveralls
    fi

notifications:
  webhooks: https://coveralls.io/webhook
